### ISSUE TITLE
Add Description variable to module

### ISSUE THREAD

**Issue by az-kennedy** [Coalfire-CF/terraform-aws-secretsmanager#8]
**Is your feature request related to a problem? Please describe.**
It would be very helpful to add an optional description variable to this module for the secrets.

**Describe the solution you'd like**
Adding description variable would help by having optional verbosity on what the purpose of the secret is for.

**Describe alternatives you've considered**
^

**Additional context**
N/A

**Comment by kourosh-forti-hands** [comment]
improvement added here: https://github.com/Coalfire-CF/terraform-aws-secretsmanager/issues/8
